version: "3.8"
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  polar-postgres:
    image: "postgres:14.9"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_UESR=ft
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=polardb_catalog
